dist: trusty
sudo: required 

language: python
python:
  - "2.7"
  
cache:
  pip: true
  directories:
  - $HOME/.ccache
  
before_install:
  - sudo apt update
  - sudo apt install mpi-default-bin mpi-default-dev ccache
  - sudo ln -s ccache /usr/local/bin/mpic++
  - export PATH=/usr/lib/ccache:${PATH}
  - ccache -s
  
install:
  - ./install_lammps.sh
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest
  - pylint simlammps -E

after_success:
  - pip install codecov
  - codecov
