language: python
python:
  - "2.7"

env:
  - SIMPHONY_VERSION=0.2.0
  - SIMPHONY_VERSION=master
matrix:
  allow_failures:
    - env: SIMPHONY_VERSION=master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mpi-default-bin mpi-default-dev

install:
  # build and install lammps
  - ./install_external.sh
  - export PATH=$PATH:$PWD/mylammps/src/:$PWD/myliggghts/src/

  - pip install -r dev_requirements.txt
  - pip install git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
  - pip install -r doc_requirements.txt
  - python setup.py develop

script:
  - flake8 --exclude=mylammps,myliggghts .
  - coverage run -m unittest discover
  - python setup.py build_sphinx
  - cd examples/dem_billiards/; python dem_billiards.py

after_success:
  - pip install codecov
  - codecov
