language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mpi-default-bin mpi-default-dev

  # LAMMPS
  #  - build lammps as shared library
  #  - and install LAMMPS python wrapper
  - git clone git://git.lammps.org/lammps-ro.git mylammps
  # checkout a recent stable version (from 28 June 2014)
  - cd mylammps/src && git checkout r12164
  # make shared library for python
  - make makeshlib && make -f Makefile.shlib ubuntu_simple
  - cd ../python && sudo python install.py /usr/lib/ $VIRTUAL_ENV/lib/python2.7/site-packages/
  # make lammps executable and add to path
  - cd ../src
  - make ubuntu_simple
  - ln -s lmp_ubuntu_simple lammps
  - export PATH=$TRAVIS_BUILD_DIR/mylammps/src/:$PATH
  - cd $TRAVIS_BUILD_DIR

  # use special branch on forked repostory of simphony-common
  # as lammps-md uses some CUDS-keywords (CUBA) that aren't
  # approved or added to simphony-common yet.
  - pip install git+git://github.com/nathanfranklin/simphony-common.git@lammps_md_cuba#egg=simphony

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - python setup.py develop

script:
  - flake8 --exclude=mylammps .
  - coverage run -m unittest discover
  - coverage report
