language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mpi-default-bin mpi-default-dev

install:
  # build and install lammps
  - ./install_external.sh
  - export PATH=$PATH:$PWD/mylammps/src/

  - pip install -r dev_requirements.txt
  - pip install -r doc_requirements.txt
  - pip install coveralls
  - python setup.py develop

script:
  - flake8 --exclude=mylammps .
  - coverage run -m unittest discover
  - python setup.py build_sphinx

after_success:
  - coveralls
