language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
    # TODO lammps
    # TODO simphony
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - flake8 .
  - coverage run -m unittest discover
  - coverage report
